# NSGA-Best3 (~105M, 7L, Gen33 Ind1) — rotary + peri-ln
- n_layer: 7
  n_embd: 768
  block_size: 1024
  use_concat_heads: true
  mlp_variant: swiglu
  use_abs_pos_embeddings: false
  use_rotary_embeddings: true
  bias: false
  wte_weight_tying: true
  use_pre_ln: true
  use_peri_ln: true
  use_post_ln: false
  n_head_layerlist: [8, 8, 8, 8, 8, 8, 12]
  n_kv_group_layerlist: [2, 2, 2, 4, 4, 4, 12]
  mlp_size_layerlist: [768, 768, 768, 3584, 3584, 3584, 1280]
  n_qk_head_dim_layerlist: [320, 320, 320, 256, 256, 256, 224]
  n_v_head_dim_layerlist: [512, 512, 512, 224, 224, 224, 256]
  n_cproj_layerlist: [1, 1, 1, 1, 1, 1, 1]
  attention_variant_layerlist:
    [infinite, infinite, infinite, infinite, infinite, infinite, identity]
